openapi: 3.0.3 
info:
  title: WASAPhoto backend REST APIs
  description: WASAPhoto APIs
  version: "0.0.1"
components:
  responses:
    BadRequest: 
      description: |-
        The request was not compliant with the documentation
        (eg. missing fields, etc).
    InternalServerError: 
      description: |-
        The server encountered an internal error.
        Further info in server logs.
    UsernameNotAvailable:
      description: The username is not available 
  parameters:
    username:
      schema:
        type: string 
        pattern: 'ˆ.*?$' 
        minLength: 3 
        maxLength: 16
        example: Maria 
      name: username
      in: path 
      required: true

  schemas:
    username:
      title: username
      type: string
      pattern: 'ˆ.*?$' 
      minLength: 3 
      maxLength: 16
      example: Maria 
    access-token:
      title: Authorization-token
      description: The user identifier for the authorization
      type: object
      properties:
        identifier:
          type: string
          example: "abcdef012345"
    photo:
      title: photo
      description: An object containing the photo file, its unique id and a caption
      type: object
      properties:
        id:
          description: Unique image identifier
          type: integer
          example: 1
          readOnly: true
        image:
          description: The image file
          type: string
          format: binary
        caption:
          description: The image's caption
          type: string
          example: "Visiting CERN"
        

    



paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user 
      description: |-
          If the user does not exist, it will be created,
          and an identifier is returned.
          If the user exists, the user identifier is returned.
      operationId: doLogin 
      requestBody:
        description: User details 
        content:
          application/json: 
            schema: 
              type: object 
              properties:
                name:
                  type: string 
                  example: Maria 
                  pattern: 'ˆ.*?$' 
                  minLength: 3 
                  maxLength: 16
        required: true 
      responses:
        '201':
          description: User log-in action successful 
          content:
              application/json: 
                schema: {$ref: "#/components/schemas/access-token"}

  /session/{username}:
    parameters:
      - $ref: "#/components/parameters/username"
    put:
      tags: ["username"]
      summary: changes username
      description: |-
        Takes the new username in the content and if it is available the new username is setted
        and returns a new identifier in the content
      operationId: setMyUsername
      requestBody:
        description: new username and authentication token
        content:
          application/json:
            schema:
              type: object
              properties:
                access-token: {$ref: "#/components/schemas/access-token"}
                newusername: {$ref: "#/components/schemas/username"}
      responses:
        "200":
          description: Username changed successfully
          content: 
            application/json:
              schema: {$ref: "#/components/schemas/access-token"}
        "409": {$ref: "#/components/responses/UsernameNotAvailable"}
        "400": {$ref: "#/components/responses/BadRequest"}
        "500": {$ref: "#/components/responses/InternalServerError"}


  /session/{username}/media/:
    parameters: 
      - $ref: "#/components/parameters/username"
    post:
      tags: ["photos"]
      summary: Upload a new photo on the profile
      description: |-
        Adds a photo to the stream of photos of the profile
      operationId: uploadPhoto
      requestBody:
        description: photo and authentication token
        content:
          image/png: 
            schema:
              type: object
              properties:
                photo: {$ref: "#/components/schemas/photo"}
                access-token: {$ref: "#/components/schemas/access-token"}
        required: true

      responses:
        "201":
          description: photo uploaded successfully
          content:
            application/json:
              schema: {$ref: "#/components/schemas/photo"}


        "400": {$ref: "#/components/responses/BadRequest"}
        "500": {$ref: "#/components/responses/InternalServerError"}
    
        